exclude: '^docs/conf.py'

repos:
- repo: https://github.com/python/black
  rev: 19.3b0
  hooks:
  - id: black
    language_version: python3.6

- repo: https://github.com/asottile/blacken-docs
  rev: v1.1.0
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==19.3b0]

- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: mixed-line-ending
    args: ['--fix=no']
  - id: flake8
    args: ['--max-line-length=88']  # default of Black

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.4
  hooks:
  - id: isort
